import { BookCategory } from './interfaces/book-category';

export const CATEGORY_LIST: BookCategory[] = [
  { categoryName: 'ANTIQUES & COLLECTIBLES', category: 'Dr Nice' },
  { categoryName: 'ARCHITECTURE', category: 'Dr Nice' },
  { categoryName: 'ART', category: 'Dr Nice' },
  { categoryName: 'BIBLES', category: 'Dr Nice' },
  { categoryName: 'BIOGRAPHY & AUTOBIOGRAPHY', category: 'Dr Nice' },
  { categoryName: 'BODY, MIND & SPIRIT', category: 'Dr Nice' },
  { categoryName: '11', category: 'Dr Nice' },
  { categoryName: '11', category: 'Dr Nice' },
  { categoryName: '11', category: 'Dr Nice' },
  { categoryName: '11', category: 'Dr Nice' },
  { categoryName: '11', category: 'Dr Nice' },
  { categoryName: '11', category: 'Dr Nice' },
  { categoryName: '11', category: 'Dr Nice' },
  { categoryName: '11', category: 'Dr Nice' },
  { categoryName: '11', category: 'Dr Nice' },
  { categoryName: '11', category: 'Dr Nice' },
  { categoryName: '11', category: 'Dr Nice' },
  { categoryName: '11', category: 'Dr Nice' },
  { categoryName: '11', category: 'Dr Nice' },
  { categoryName: '11', category: 'Dr Nice' },
  { categoryName: '11', category: 'Dr Nice' },
  { categoryName: '11', category: 'Dr Nice' },
  { categoryName: '11', category: 'Dr Nice' },
  { categoryName: '11', category: 'Dr Nice' },
  { categoryName: '11', category: 'Dr Nice' },
  { categoryName: '11', category: 'Dr Nice' },
  { categoryName: '11', category: 'Dr Nice' },
  { categoryName: '11', category: 'Dr Nice' },
  { categoryName: '11', category: 'Dr Nice' },
  { categoryName: '11', category: 'Dr Nice' },
  { categoryName: '11', category: 'Dr Nice' },
  { categoryName: '11', category: 'Dr Nice' },
  { categoryName: '11', category: 'Dr Nice' },
  { categoryName: '11', category: 'Dr Nice' },
  { categoryName: '11', category: 'Dr Nice' },
  { categoryName: '11', category: 'Dr Nice' },
  { categoryName: '11', category: 'Dr Nice' },
  { categoryName: '11', category: 'Dr Nice' },
  { categoryName: '11', category: 'Dr Nice' },
];
